### ISSUE TITLE
Apostrophes were not distinguished

### ISSUE THREAD

**Issue by mblabs** [symphonycms/uniqueinputfield#6]
Terms with apostrophes were recognised as equal (ex. 1. that's 2. thats)

**Comment by DavidOliver** [comment]
Is this because this extension only checks for uniqueness of the handle, and not the value, with `isHandleUnique`?

**Comment by nitriques** [comment]
I find it pretty weird that the value is not checked (only the handle...)

@brendo would you remember why ?

**Comment by michael-e** [comment]
I guess this is because the main goal of this extensions is to prevent entries from having the same URL, i.e. having the same handle.

**Comment by nitriques** [comment]
So should we rename it to unique handle field then ? I was quite confused at first...

**Comment by michael-e** [comment]
Hmmm, no, I wouldn't rename the field which is heavily used, probably. One might improve the README. :-) It states:

> however it enforces uniqueness and you …

One might write:

> however it enforces uniqueness of the handle and you

**Comment by michael-e** [comment]
BTW, there is a typo in the meta XML:

```xml
<description>Force unique values or handles</description>
```

Shouldn't this be:

```xml
<description>Force unique values for handles</description>
```

or simply:

```xml
<description>Force unique handles</description>
```

**Comment by nitriques** [comment]
Agreed.
