### ISSUE TITLE
Duplicate entries created?

### ISSUE THREAD

**Issue by patrickyan** [symphonycms/uniqueinputfield#8]
I have run into a situation twice where two of the same entries are created. I thought unique input should stop this from happening? In testing, it seems like I cannot reproduce this. However, my users have been able to post entries with the same text in a unique input. It might be if two requests happen at the same time? (But this should still not happen)

**Comment by DavidOliver** [comment]
@michael-e, it looks to me like this extension doesn't use the core input field's `createTable` method, and has its own `CREATE TABLE` SQL which is run on installation, which doesn't set a `UNIQUE KEY`.

**Comment by michael-e** [comment]
The `CREATE TABLE` in the extension driver is not the problem. Some fields use their own `CREATE TABLE` in the field class (which is used for the `sym_data_` tables) — these are the problem. I don't see one here. Do you see a `createTable` method?

**Comment by DavidOliver** [comment]
Ah, of course. I wasn't thinking very well/much.

**Comment by michael-e** [comment]
I always mess these up in my head. :-)

**Comment by nitriques** [comment]
Closing since it's fixed!
